# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-17 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.IntegerField()),
                ('stock_name', models.CharField(max_length=100)),
            ],
        ),
    ]
